# Generated by Django 4.2.13 on 2024-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0003_rename_measures_cleanlinessorderapartment_cold_room_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanlinessorderapartment',
            old_name='cold_room_comment',
            new_name='measures',
        ),
        migrations.RemoveField(
            model_name='cleanlinessorderapartment',
            name='floor_comment',
        ),
        migrations.RemoveField(
            model_name='cleanlinessorderapartment',
            name='garbage_comment',
        ),
        migrations.RemoveField(
            model_name='cleanlinessorderapartment',
            name='shelf_comment',
        ),
        migrations.RemoveField(
            model_name='cleanlinessorderapartment',
            name='washroom_kitchen_comment',
        ),
        migrations.RemoveField(
            model_name='cleanlinessorderapartment',
            name='wc_comment',
        ),
    ]
