# Generated by Django 4.2.13 on 2024-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0004_rename_cold_room_comment_cleanlinessorderapartment_measures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBikeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date the condition was reported')),
                ('calendar_week', models.CharField(help_text='The calendar week based on the selected date', max_length=20)),
                ('store', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], help_text='The store where the bikes are located', max_length=10)),
                ('bike_condition', models.TextField(help_text='The condition of the bikes and actions to be taken')),
            ],
            options={
                'verbose_name': 'E-Bike Condition',
                'verbose_name_plural': 'E-Bike Conditions',
                'ordering': ['-date'],
            },
        ),
    ]
