# Generated by Django 4.2.13 on 2024-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0005_ebikecondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonderreinigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('store', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], max_length=10, verbose_name='Store')),
                ('ventilation', models.CharField(choices=[('yes', 'Ja'), ('no', 'Nein')], max_length=3, verbose_name='Lüftungsgitter Kühlzelle')),
                ('spiderwebs', models.CharField(choices=[('yes', 'Ja'), ('no', 'Nein')], max_length=3, verbose_name='Spinnweben Eingangsbereich')),
                ('washer', models.CharField(choices=[('yes', 'Ja'), ('no', 'Nein')], max_length=3, verbose_name='Waschmaschine Flusensieb reinigen')),
            ],
            options={
                'verbose_name': 'Sonderreinigung',
                'verbose_name_plural': 'Sonderreinigungen',
                'ordering': ['-date'],
            },
        ),
    ]
