# Generated by Django 4.2.13 on 2024-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0006_sonderreinigung'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonderreinigung',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
