# Generated by Django 4.2.13 on 2024-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0007_sonderreinigung_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='measures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
