# Generated by Django 4.2.13 on 2024-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0009_cleanlinessorderstorage_measures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='cold_room_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='floor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='garbage_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='shelf_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='washroom_kitchen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='wc_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitchenlunchtask',
            name='task_laundry_drying',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True, verbose_name='Fresh laundry hung to dry'),
        ),
    ]
