# Generated by Django 4.2.13 on 2024-10-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0010_cleanlinessorderapartment_cold_room_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenlatetask',
            name='washing_machine_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the person who started the washing machine today'),
        ),
        migrations.AddField(
            model_name='kitchenlatetask',
            name='washing_machine_status',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True, verbose_name='Washing machine started'),
        ),
    ]
