# Generated by Django 4.2.13 on 2024-11-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0011_kitchenlatetask_washing_machine_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalinventory',
            name='dip_tuete',
            field=models.PositiveIntegerField(default=0, verbose_name='Dip Tüte (Einheit 50 St.)'),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='kuerbiskerne',
            field=models.PositiveIntegerField(default=0, verbose_name='Kürbiskerne (Tüte)'),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='trueffel_mayo',
            field=models.PositiveIntegerField(default=0, verbose_name='Trüffel Mayo (Flasche)'),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='zwiebel_chutney',
            field=models.PositiveIntegerField(default=0, verbose_name='Zwiebel Chutney (Glas)'),
        ),
    ]
