# Generated by Django 4.2.13 on 2024-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0012_terminalinventory_dip_tuete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbeforedatecheck',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='pflaster',
            field=models.PositiveIntegerField(default=0, verbose_name='Pflaster (Stück)'),
        ),
        migrations.AlterField(
            model_name='kitchenlate',
            name='old_balls_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many of these are new'),
        ),
    ]
