# Generated by Django 4.2.13 on 2024-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0014_rename_store_ebikecondition_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebikecondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
