# Generated by Django 4.2.13 on 2024-12-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0016_sonderreinigung_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonderreinigung',
            old_name='store',
            new_name='location',
        ),
    ]
