# Generated by Django 4.2.13 on 2024-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0017_rename_store_sonderreinigung_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='cold_room_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='floor_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='garbage_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='shelf_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='washroom_kitchen_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='wc_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
