# Generated by Django 4.2.13 on 2024-12-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0018_cleanlinessorderapartment_cold_room_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlinessorderapartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewchecklistsapartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewchecklistskitchen',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewchecklistsstorage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewcheckliststerminal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
