# Generated by Django 4.2.13 on 2024-12-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0023_cleanlinessorderkitchen_bottom_sink_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='bottom_sink_image',
            field=models.ImageField(blank=True, null=True, upload_to='bottom_sink_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='extractor_hood_image',
            field=models.ImageField(blank=True, null=True, upload_to='extractor_hood_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='kav_image',
            field=models.ImageField(blank=True, null=True, upload_to='kav_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='refrigerator_image',
            field=models.ImageField(blank=True, null=True, upload_to='refrigerator_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='refrigerators_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='refrigerators_back_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='tables_downstairs_image',
            field=models.ImageField(blank=True, null=True, upload_to='tables_downstairs_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderkitchen',
            name='tiles_image',
            field=models.ImageField(blank=True, null=True, upload_to='tiles_images/'),
        ),
    ]
