# Generated by Django 4.2.13 on 2024-12-30 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0024_cleanlinessorderkitchen_bottom_sink_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanlinessorderapartment',
            name='floor_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
