# Generated by Django 4.2.13 on 2025-02-16 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0025_alter_cleanlinessorderapartment_floor_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalinventory',
            name='kuerbiskerne',
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='floor_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/floor/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='floor_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='garbage_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/garbage/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='garbage_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='inventory_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/inventory/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='inventory_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='tidiness_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/tidiness/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderstorage',
            name='tidiness_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='counter_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='counter_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='floor_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='floor_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='lamps_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='lamps_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='refrigerator_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='refrigerator_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='tables_chairs_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='tables_chairs_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='tiles_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='tiles_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='windows_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleanliness_images/'),
        ),
        migrations.AddField(
            model_name='cleanlinessorderterminal',
            name='windows_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='ebikecondition',
            name='bike_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='ebikecondition',
            name='bike_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='ebikecondition',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='spiderwebs_image',
            field=models.ImageField(blank=True, null=True, upload_to='spiderwebs_images/'),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='spiderwebs_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='ventilation_image',
            field=models.ImageField(blank=True, null=True, upload_to='ventilation_images/'),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='ventilation_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='washer_image',
            field=models.ImageField(blank=True, null=True, upload_to='washer_images/'),
        ),
        migrations.AddField(
            model_name='sonderreinigung',
            name='washer_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='blaue_rolle',
            field=models.PositiveIntegerField(default=0, verbose_name='Blaue Rolle (Stück)'),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='tomatendose_pumarole_dolce',
            field=models.PositiveIntegerField(default=0, verbose_name='Tomatendose Pumarole Dolce'),
        ),
        migrations.AddField(
            model_name='terminalinventory',
            name='tomatendose_san_marzano_dop',
            field=models.PositiveIntegerField(default=0, verbose_name='Tomatendose San Marzano D.O.P.'),
        ),
        migrations.AlterField(
            model_name='cleanlinessorderapartment',
            name='floor_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
